import { CalendarClock, ExternalLink, X } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { formatDaysRemaining, formatExpiryDate } from '../../utils/expiryUtils';
import { ExpiryStatusBadge } from './ExpiryStatusBadge';
import { formatPackagingPreview } from '../../utils/medicineCalculations';
import { getPackaging } from '../../utils/productModel';

const Detail = ({ label, value }) => <div><dt className="text-[11px] font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">{label}</dt><dd className="mt-1 text-sm text-slate-900 dark:text-slate-100">{value || '—'}</dd></div>;

export const ExpiryDetailsModal = ({ entry, onClose }) => {
  const navigate = useNavigate();
  if (!entry) return null;
  const { product, batch } = entry;
  const packaging = getPackaging(product);
  return <div className="fixed inset-0 z-50 flex items-center justify-center p-4" role="dialog" aria-modal="true" aria-labelledby="expiry-details-title"><button type="button" aria-label="Close expiry details" onClick={onClose} className="absolute inset-0 bg-slate-950/40 backdrop-blur-xs" /><div className="relative w-full max-w-2xl overflow-hidden rounded-2xl border border-slate-200/70 bg-white shadow-2xl dark:border-slate-800 dark:bg-slate-900"><div className="flex items-start justify-between border-b border-slate-200/70 p-5 dark:border-slate-800"><div className="flex gap-3"><div className="rounded-xl bg-blue-50 p-2.5 text-blue-600 dark:bg-blue-950/60 dark:text-blue-400"><CalendarClock className="h-5 w-5" /></div><div><h3 id="expiry-details-title" className="font-bold text-slate-900 dark:text-white">Expiry Details</h3><p className="mt-0.5 text-xs text-slate-500 dark:text-slate-400">{product.name}</p></div></div><button type="button" onClick={onClose} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100 hover:text-slate-700 dark:hover:bg-slate-800 dark:hover:text-slate-200"><X className="h-5 w-5" /></button></div><div className="space-y-5 p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-slate-50 p-4 dark:bg-slate-800/60"><div><ExpiryStatusBadge status={entry.status} /><p className="mt-2 text-sm font-semibold text-slate-800 dark:text-slate-100">{formatDaysRemaining(entry.daysRemaining)}</p></div><div className="text-right"><p className="text-xs text-slate-500">Expiry date</p><p className="mt-1 text-sm font-semibold text-slate-900 dark:text-white">{formatExpiryDate(entry.expiryDate)}</p></div></div><dl className="grid grid-cols-1 gap-4 sm:grid-cols-2"><Detail label="Generic / Brand" value={[product.genericName, product.brandName].filter(Boolean).join(' · ')} /><Detail label="Batch Number" value={entry.batchNumber} /><Detail label="Available Stock" value={entry.stockLabel} /><Detail label="Supplier" value={entry.supplierName} /><Detail label="Packaging" value={formatPackagingPreview(packaging)} /><Detail label="Purchase Date" value={batch?.purchaseDate ? formatExpiryDate(batch.purchaseDate.slice(0, 10)) : null} /></dl></div><div className="flex justify-end gap-3 border-t border-slate-200/70 p-5 dark:border-slate-800"><button type="button" onClick={onClose} className="rounded-xl px-4 py-2.5 text-sm font-semibold text-slate-600 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-800">Close</button><button type="button" onClick={() => navigate('/inventory')} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-blue-700"><ExternalLink className="h-4 w-4" />View inventory</button></div></div></div>;
};
