import { ArrowUpDown, Eye, PackageSearch } from 'lucide-react';
import { Pagination } from '../common/Pagination';
import { ExpiryStatusBadge } from './ExpiryStatusBadge';
import { formatDaysRemaining, formatExpiryDate } from '../../utils/expiryUtils';

const columns = [['name', 'Medicine'], ['batchNumber', 'Batch'], ['expiryDate', 'Expiry Date'], ['daysRemaining', 'Days Remaining'], ['stockUnits', 'Available Stock'], ['status', 'Status']];

export const ExpiryTable = ({ entries, totalItems, page, pageSize, sortConfig, onSort, onPageChange, onView, hasFilters }) => {
  if (!entries.length) return <section className="flex flex-col items-center rounded-2xl border border-slate-200/70 bg-white p-12 text-center shadow-xs dark:border-slate-800 dark:bg-slate-900"><PackageSearch className="mb-3 h-10 w-10 text-slate-300 dark:text-slate-700" /><h3 className="text-sm font-bold text-slate-700 dark:text-slate-200">{hasFilters ? 'No medicines match your filters' : 'No expiry records to track'}</h3><p className="mt-1 text-xs text-slate-500 dark:text-slate-400">{hasFilters ? 'Try adjusting your search or filter selections.' : 'Expiry information will appear here when it is available in inventory.'}</p></section>;
  return <section className="rounded-2xl border border-slate-200/70 bg-white p-5 shadow-xs dark:border-slate-800 dark:bg-slate-900"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead><tr className="border-b border-slate-100 dark:border-slate-800">{columns.map(([key, label]) => <th key={key} className="pb-3 pr-4 text-left"><button type="button" onClick={() => onSort(key)} className="flex items-center gap-1.5 text-[11px] font-bold uppercase tracking-wider text-slate-500 hover:text-slate-800 dark:text-slate-400 dark:hover:text-white">{label}<ArrowUpDown className={`h-3.5 w-3.5 ${sortConfig.key === key ? 'text-blue-600' : 'opacity-40'}`} /></button></th>)}<th className="pb-3 text-right text-[11px] font-bold uppercase tracking-wider text-slate-500">Actions</th></tr></thead><tbody>{entries.map((entry) => <tr key={entry.id} onClick={() => onView(entry)} className="cursor-pointer border-b border-slate-50 transition-colors last:border-0 hover:bg-slate-50/80 dark:border-slate-800/40 dark:hover:bg-slate-800/30"><td className="py-3.5 pr-4"><div className="font-semibold text-slate-900 dark:text-slate-100">{entry.product.name}</div><div className="mt-0.5 text-xs text-slate-500">{[entry.product.genericName, entry.product.brandName].filter(Boolean).join(' · ') || '—'}</div></td><td className="py-3.5 pr-4 font-mono text-xs text-slate-600 dark:text-slate-400">{entry.batchNumber}</td><td className="py-3.5 pr-4 text-slate-700 dark:text-slate-300">{formatExpiryDate(entry.expiryDate)}</td><td className="py-3.5 pr-4 font-medium text-slate-700 dark:text-slate-300">{formatDaysRemaining(entry.daysRemaining)}</td><td className="py-3.5 pr-4 text-slate-700 dark:text-slate-300">{entry.stockLabel}</td><td className="py-3.5 pr-4"><ExpiryStatusBadge status={entry.status} /></td><td className="py-3.5 text-right"><button type="button" onClick={(event) => { event.stopPropagation(); onView(entry); }} aria-label={`View ${entry.product.name} expiry details`} className="rounded-lg p-1.5 text-slate-400 hover:bg-blue-50 hover:text-blue-600 dark:hover:bg-blue-950/50"><Eye className="h-4 w-4" /></button></td></tr>)}</tbody></table></div><Pagination currentPage={page} totalPages={Math.max(1, Math.ceil(totalItems / pageSize))} totalItems={totalItems} pageSize={pageSize} onPageChange={onPageChange} /></section>;
};
