import { useState } from 'react';
import { X } from 'lucide-react';

const blankSupplier = { supplierName: '', companyName: '', gstNumber: '', drugLicenseNumber: '', contactPerson: '', phoneNumber: '', email: '', address: '', city: '', state: '', pincode: '', notes: '', status: 'Active' };
const fields = [['supplierName', 'Supplier Name'], ['companyName', 'Company Name'], ['gstNumber', 'GST Number'], ['drugLicenseNumber', 'Drug License Number'], ['contactPerson', 'Contact Person'], ['phoneNumber', 'Phone Number'], ['email', 'Email'], ['city', 'City'], ['state', 'State'], ['pincode', 'Pincode']];

export const SupplierModal = ({ supplier, onClose, onSave }) => {
  const [form, setForm] = useState(supplier || blankSupplier);
  const [error, setError] = useState('');
  const update = (event) => setForm((current) => ({ ...current, [event.target.name]: event.target.value }));
  const submit = (event) => { event.preventDefault(); if (!form.supplierName.trim() || !form.companyName.trim() || !form.contactPerson.trim() || !form.phoneNumber.trim()) { setError('Supplier name, company, contact person, and phone number are required.'); return; } onSave({ ...form, supplierName: form.supplierName.trim(), companyName: form.companyName.trim() }); };
  return <div className="fixed inset-0 z-50 flex items-center justify-center p-4" role="dialog" aria-modal="true"><button type="button" onClick={onClose} className="absolute inset-0 bg-slate-950/40" /><form onSubmit={submit} className="relative w-full max-w-3xl max-h-[calc(100vh-2rem)] overflow-y-auto bg-white dark:bg-slate-900 rounded-2xl border border-slate-200/70 dark:border-slate-800 shadow-2xl"><div className="sticky top-0 flex items-center justify-between p-5 bg-white dark:bg-slate-900 border-b border-slate-200/70 dark:border-slate-800"><h3 className="text-base font-bold text-slate-900 dark:text-white">{supplier ? 'Edit Supplier' : 'Add Supplier'}</h3><button type="button" onClick={onClose} className="p-2 text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg"><X className="w-5 h-5" /></button></div><div className="p-5 sm:p-6 grid grid-cols-1 sm:grid-cols-2 gap-4">{fields.map(([name, label]) => <label key={name}><span className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1.5">{label}</span><input name={name} value={form[name] || ''} onChange={update} className="w-full px-3 py-2.5 text-sm bg-slate-50 dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700" /></label>)}<label className="sm:col-span-2"><span className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1.5">Address</span><textarea name="address" value={form.address || ''} onChange={update} rows="2" className="w-full px-3 py-2.5 text-sm bg-slate-50 dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700" /></label><label className="sm:col-span-2"><span className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1.5">Notes</span><textarea name="notes" value={form.notes || ''} onChange={update} rows="2" className="w-full px-3 py-2.5 text-sm bg-slate-50 dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700" /></label><label><span className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1.5">Status</span><select name="status" value={form.status} onChange={update} className="w-full px-3 py-2.5 text-sm bg-slate-50 dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700"><option>Active</option><option>Inactive</option></select></label>{error && <p className="sm:col-span-2 text-xs text-rose-600">{error}</p>}</div><div className="sticky bottom-0 flex justify-end gap-3 p-5 bg-white dark:bg-slate-900 border-t border-slate-200/70 dark:border-slate-800"><button type="button" onClick={onClose} className="px-4 py-2.5 text-sm font-semibold text-slate-600 dark:text-slate-300">Cancel</button><button className="px-4 py-2.5 text-sm font-semibold text-white bg-blue-600 rounded-xl">{supplier ? 'Update Supplier' : 'Save Supplier'}</button></div></form></div>;
};
