import { Activity, ShieldCheck } from 'lucide-react';
import { useLocation, useNavigate } from 'react-router-dom';
import { useState } from 'react';
import { LoginForm } from '../components/auth/LoginForm';
import { useAuth } from '../hooks/useAuth';

export const LoginPage = () => {
  const { login } = useAuth(); const navigate = useNavigate(); const location = useLocation(); const [error, setError] = useState(''); const [isLoading, setIsLoading] = useState(false);
  const submit = async (email, password) => { setIsLoading(true); setError(''); try { await login(email, password); navigate(location.state?.from?.pathname || '/', { replace: true }); } catch (reason) { setError(reason.message || 'Unable to sign in.'); } finally { setIsLoading(false); } };
  return <main className="min-h-screen bg-slate-50 p-4 dark:bg-slate-950 sm:p-8"><div className="mx-auto flex min-h-[calc(100vh-2rem)] max-w-5xl overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-xl shadow-slate-200/50 dark:border-slate-800 dark:bg-slate-900 dark:shadow-none"><section className="hidden w-5/12 flex-col justify-between bg-blue-600 p-10 text-white lg:flex"><div><div className="flex items-center gap-3"><div className="rounded-xl bg-white/15 p-2.5"><Activity className="h-6 w-6" /></div><span className="text-xl font-bold">MedTrack</span></div><h1 className="mt-16 text-4xl font-bold tracking-tight">Pharmacy operations, in one secure workspace.</h1><p className="mt-5 text-blue-100">Sign in to manage inventory, billing, purchases, and your pharmacy settings.</p></div><div className="flex items-center gap-2 text-sm text-blue-100"><ShieldCheck className="h-4 w-4" />Frontend demo authentication — replace with FastAPI/JWT in production.</div></section><section className="flex flex-1 items-center justify-center p-6 sm:p-12"><div className="w-full max-w-md"><div className="lg:hidden"><div className="flex items-center gap-2 text-blue-600"><Activity className="h-6 w-6" /><span className="text-xl font-bold">MedTrack</span></div></div><h2 className="mt-8 text-2xl font-bold text-slate-900 dark:text-white">Welcome back</h2><p className="mt-2 text-sm text-slate-500 dark:text-slate-400">Sign in to continue to your workspace.</p><div className="mt-8"><LoginForm onSubmit={submit} isLoading={isLoading} error={error} /></div><p className="mt-5 text-xs text-slate-500 dark:text-slate-400">Local demo account: use one of the email addresses configured by your administrator.</p></div></section></div></main>;
};
