// API Configuration
export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000';

export const API_ENDPOINTS = {
  auth: {
    register: '/api/v1/auth/register',
    login: '/api/v1/auth/login',
    me: '/api/v1/auth/me',
    pharmacies: '/api/v1/auth/pharmacies',
    selectPharmacy: '/api/v1/auth/select-pharmacy',
    currentPharmacy: '/api/v1/auth/current-pharmacy',
  },
  medicines: {
    list: '/api/v1/medicines',
    create: '/api/v1/medicines',
    get: (id) => `/api/v1/medicines/${id}`,
    update: (id) => `/api/v1/medicines/${id}`,
    delete: (id) => `/api/v1/medicines/${id}`,
  },
  categories: {
    list: '/api/v1/medicines/categories',
    create: '/api/v1/medicines/categories',
    get: (id) => `/api/v1/medicines/categories/${id}`,
    update: (id) => `/api/v1/medicines/categories/${id}`,
    delete: (id) => `/api/v1/medicines/categories/${id}`,
  },
  batches: {
    list: '/api/v1/medicines/batches',
    create: '/api/v1/medicines/batches',
    get: (id) => `/api/v1/medicines/batches/${id}`,
    update: (id) => `/api/v1/medicines/batches/${id}`,
    delete: (id) => `/api/v1/medicines/batches/${id}`,
  },
  suppliers: {
    list: '/api/v1/suppliers',
    create: '/api/v1/suppliers',
    get: (id) => `/api/v1/suppliers/${id}`,
    update: (id) => `/api/v1/suppliers/${id}`,
    delete: (id) => `/api/v1/suppliers/${id}`,
  },
  purchases: {
    list: '/api/v1/purchases',
    create: '/api/v1/purchases',
    get: (id) => `/api/v1/purchases/${id}`,
    update: (id) => `/api/v1/purchases/${id}`,
    delete: (id) => `/api/v1/purchases/${id}`,
    receive: (id) => `/api/v1/purchases/${id}/receive`,
  },
  invoices: {
    list: '/api/v1/invoices',
    create: '/api/v1/invoices',
    get: (id) => `/api/v1/invoices/${id}`,
    update: (id) => `/api/v1/invoices/${id}`,
    complete: (id) => `/api/v1/invoices/${id}/complete`,
    cancel: (id) => `/api/v1/invoices/${id}`,
    customers: '/api/v1/invoices/customers',
  },
  returns: {
    list: '/api/v1/returns',
    create: '/api/v1/returns',
    get: (id) => `/api/v1/returns/${id}`,
    complete: (id) => `/api/v1/returns/${id}/complete`,
    cancel: (id) => `/api/v1/returns/${id}`,
    delete: (id) => `/api/v1/returns/${id}`,
  },
  settings: {
    get: '/api/v1/settings/',
    update: '/api/v1/settings/',
  },
  expiry: {
    list: '/api/v1/expiry/',
    summary: '/api/v1/expiry/summary',
    expired: '/api/v1/expiry/expired',
    expiringSoon: '/api/v1/expiry/expiring-soon',
  },
  alerts: {
    list: '/api/v1/alerts/',
    summary: '/api/v1/alerts/summary',
    lowStock: '/api/v1/alerts/low-stock',
  },
  reports: {
    sales: '/api/v1/reports/sales',
    salesSummary: '/api/v1/reports/sales/summary',
    purchases: '/api/v1/reports/purchases',
    purchasesSummary: '/api/v1/reports/purchases/summary',
    cogs: '/api/v1/reports/cogs',
    cogsSummary: '/api/v1/reports/cogs/summary',
    profit: '/api/v1/reports/profit',
    profitSummary: '/api/v1/reports/profit/summary',
    dashboardSummary: '/api/v1/reports/summary',
    topMedicines: '/api/v1/reports/top-medicines',
    topSuppliers: '/api/v1/reports/top-suppliers',
  },
};