"""add_stock_allocation

Revision ID: 475f6427ca3b
Revises: 7bab1f411163
Create Date: 2026-08-14 20:20:45.073726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '475f6427ca3b'
down_revision: Union[str, Sequence[str], None] = '7bab1f411163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_allocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('medicine_id', sa.Uuid(), nullable=False),
    sa.Column('inventory_batch_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pharmacy_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_batch_id'], ['inventory_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_allocations_inventory_batch_id'), 'stock_allocations', ['inventory_batch_id'], unique=False)
    op.create_index(op.f('ix_stock_allocations_medicine_id'), 'stock_allocations', ['medicine_id'], unique=False)
    op.create_index(op.f('ix_stock_allocations_pharmacy_id'), 'stock_allocations', ['pharmacy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_allocations_pharmacy_id'), table_name='stock_allocations')
    op.drop_index(op.f('ix_stock_allocations_medicine_id'), table_name='stock_allocations')
    op.drop_index(op.f('ix_stock_allocations_inventory_batch_id'), table_name='stock_allocations')
    op.drop_table('stock_allocations')
    # ### end Alembic commands ###
