"""add_pharmacy_settings

Revision ID: 9b4e5d6a7c8f
Revises: 8a3f2c1d9e4b
Create Date: 2026-08-18 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b4e5d6a7c8f'
down_revision: Union[str, Sequence[str], None] = '8a3f2c1d9e4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharmacy_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pharmacy_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_prefix', sa.String(), nullable=False),
    sa.Column('invoice_footer', sa.String(), nullable=True),
    sa.Column('show_gstin', sa.Boolean(), nullable=False),
    sa.Column('show_drug_license', sa.Boolean(), nullable=False),
    sa.Column('default_currency', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('date_format', sa.String(), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pharmacy_id', name='uq_pharmacy_settings_pharmacy_id')
    )
    op.create_index(op.f('ix_pharmacy_settings_pharmacy_id'), 'pharmacy_settings', ['pharmacy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pharmacy_settings_pharmacy_id'), table_name='pharmacy_settings')
    op.drop_table('pharmacy_settings')
    # ### end Alembic commands ###