// Mock inventory data — replace with Supabase/FastAPI queries in a later ticket.

import { calculateTotalUnits } from './medicineCalculations';

export const categories = [
    { id: 'pain-killers', name: 'Pain Killers', icon: 'Pill', color: 'blue' },
    { id: 'antibiotics', name: 'Antibiotics', icon: 'ShieldPlus', color: 'emerald' },
    { id: 'vitamins', name: 'Vitamins', icon: 'Sparkles', color: 'amber' },
    { id: 'syrups', name: 'Syrups', icon: 'FlaskConical', color: 'indigo' },
    { id: 'injections', name: 'Injections', icon: 'Syringe', color: 'rose' },
];

export const medicines = [
    {
        id: 'MED-1001',
        name: 'Amoxicillin 500mg',
        genericName: 'Amoxicillin',
        brandName: 'Amoxil',
        manufacturer: 'PharmaCorp Ltd',
        category: 'antibiotics',
        supplier: 'PharmaCorp Ltd',
        batchNumber: 'AMX-882',
        manufacturingDate: '2025-03-01',
        expiryDate: '2027-03-14',
        rackLocation: 'A-12',
        strength: '500mg',
        description: 'Broad-spectrum antibiotic capsule used to treat a range of bacterial infections.',
        barcode: '8901030875421',
        image: null,
        packaging: { packType: 'Strip', inventoryUnit: 'Capsule', unitsPerPack: 10 },
        stock: { currentPacks: 48, looseUnits: 4, reorderLevel: 10 },
        pricing: { purchasePricePerPack: 18.0, sellingPricePerPack: 24.0 },
        sellingOptions: { allowSellingByPack: true, allowSellingByUnit: true },
    },
    {
        id: 'MED-1002',
        name: 'Paracetamol 650mg',
        genericName: 'Paracetamol',
        brandName: 'Calpol Forte',
        manufacturer: 'MedSupply Co',
        category: 'pain-killers',
        supplier: 'MedSupply Co',
        batchNumber: 'PCM-441',
        manufacturingDate: '2025-05-01',
        expiryDate: '2026-11-02',
        rackLocation: 'B-04',
        strength: '650mg',
        description: 'Analgesic and antipyretic tablet for relief of pain and fever.',
        barcode: '8901030875422',
        image: null,
        packaging: { packType: 'Strip', inventoryUnit: 'Tablet', unitsPerPack: 10 },
        stock: { currentPacks: 6, looseUnits: 0, reorderLevel: 15 },
        pricing: { purchasePricePerPack: 6.0, sellingPricePerPack: 8.0 },
        sellingOptions: { allowSellingByPack: true, allowSellingByUnit: true },
    },
    {
        id: 'MED-1003',
        name: 'Ibuprofen 400mg',
        genericName: 'Ibuprofen',
        brandName: 'Brufen',
        manufacturer: 'PharmaCorp Ltd',
        category: 'pain-killers',
        supplier: 'PharmaCorp Ltd',
        batchNumber: 'IBU-219',
        manufacturingDate: '2025-04-10',
        expiryDate: '2026-09-28',
        rackLocation: 'B-05',
        strength: '400mg',
        description: 'NSAID tablet used to relieve pain, inflammation and fever.',
        barcode: '8901030875423',
        image: null,
        packaging: { packType: 'Strip', inventoryUnit: 'Tablet', unitsPerPack: 10 },
        stock: { currentPacks: 1, looseUnits: 5, reorderLevel: 12 },
        pricing: { purchasePricePerPack: 8.0, sellingPricePerPack: 11.0 },
        sellingOptions: { allowSellingByPack: true, allowSellingByUnit: true },
    },
    {
        id: 'MED-1004',
        name: 'Multivitamin Syrup',
        genericName: 'Multivitamin',
        brandName: 'Revital Syrup',
        manufacturer: 'MedAid Pharmaceuticals',
        category: 'syrups',
        supplier: 'MedAid NGO',
        batchNumber: 'MVT-556',
        manufacturingDate: '2025-02-15',
        expiryDate: '2026-08-20',
        rackLocation: 'C-02',
        strength: '200ml',
        description: 'Multivitamin syrup formulated to support daily nutritional needs.',
        barcode: '8901030875424',
        image: null,
        packaging: { packType: 'Bottle', inventoryUnit: 'mL', unitsPerPack: 200 },
        stock: { currentPacks: 25, looseUnits: 0, reorderLevel: 6 },
        pricing: { purchasePricePerPack: 65.0, sellingPricePerPack: 90.0 },
        sellingOptions: { allowSellingByPack: true, allowSellingByUnit: false },
    },
    {
        id: 'MED-1005',
        name: 'Ceftriaxone 1g Injection',
        genericName: 'Ceftriaxone',
        brandName: 'Rocephin',
        manufacturer: 'BioHealth Labs',
        category: 'injections',
        supplier: 'BioHealth Labs',
        batchNumber: 'CFT-330',
        manufacturingDate: '2025-01-20',
        expiryDate: '2026-08-25',
        rackLocation: 'D-01',
        strength: '1g',
        description: 'Broad-spectrum cephalosporin antibiotic administered by injection.',
        barcode: '8901030875425',
        image: null,
        packaging: { packType: 'Vial', inventoryUnit: 'mL', unitsPerPack: 10 },
        stock: { currentPacks: 40, looseUnits: 0, reorderLevel: 10 },
        pricing: { purchasePricePerPack: 42.0, sellingPricePerPack: 52.0 },
        sellingOptions: { allowSellingByPack: true, allowSellingByUnit: false },
    },
    {
        id: 'MED-1006',
        name: 'Vitamin D3 60K IU',
        genericName: 'Cholecalciferol',
        brandName: 'Uprise D3',
        manufacturer: 'NutriPharma',
        category: 'vitamins',
        supplier: 'NutriPharma',
        batchNumber: 'VTD-102',
        manufacturingDate: '2025-06-05',
        expiryDate: '2027-06-10',
        rackLocation: 'E-03',
        strength: '60,000 IU',
        description: 'Weekly vitamin D3 softgel capsule supplement for bone health.',
        barcode: '8901030875426',
        image: null,
        packaging: { packType: 'Strip', inventoryUnit: 'Capsule', unitsPerPack: 4 },
        stock: { currentPacks: 80, looseUnits: 0, reorderLevel: 15 },
        pricing: { purchasePricePerPack: 6.0, sellingPricePerPack: 8.0 },
        sellingOptions: { allowSellingByPack: true, allowSellingByUnit: true },
    },
    {
        id: 'MED-1007',
        name: 'Azithromycin 250mg',
        genericName: 'Azithromycin',
        brandName: 'Azithral',
        manufacturer: 'PharmaCorp Ltd',
        category: 'antibiotics',
        supplier: 'PharmaCorp Ltd',
        batchNumber: 'AZM-771',
        manufacturingDate: '2025-04-25',
        expiryDate: '2026-12-01',
        rackLocation: 'A-14',
        strength: '250mg',
        description: 'Macrolide antibiotic tablet used to treat bacterial respiratory infections.',
        barcode: '8901030875427',
        image: null,
        packaging: { packType: 'Strip', inventoryUnit: 'Tablet', unitsPerPack: 6 },
        stock: { currentPacks: 1, looseUnits: 2, reorderLevel: 15 },
        pricing: { purchasePricePerPack: 14.0, sellingPricePerPack: 18.6 },
        sellingOptions: { allowSellingByPack: true, allowSellingByUnit: true },
    },
    {
        id: 'MED-1008',
        name: 'Cough Syrup DX',
        genericName: 'Dextromethorphan',
        brandName: 'Corex DX',
        manufacturer: 'MedSupply Co',
        category: 'syrups',
        supplier: 'MedSupply Co',
        batchNumber: 'CSD-208',
        manufacturingDate: '2025-03-18',
        expiryDate: '2026-07-30',
        rackLocation: 'C-05',
        strength: '100ml',
        description: 'Cough suppressant syrup for relief of dry and irritating cough.',
        barcode: '8901030875428',
        image: null,
        packaging: { packType: 'Bottle', inventoryUnit: 'mL', unitsPerPack: 100 },
        stock: { currentPacks: 95, looseUnits: 0, reorderLevel: 20 },
        pricing: { purchasePricePerPack: 16.0, sellingPricePerPack: 22.0 },
        sellingOptions: { allowSellingByPack: true, allowSellingByUnit: false },
    },
    {
        id: 'MED-1009',
        name: 'Insulin Glargine',
        genericName: 'Insulin Glargine',
        brandName: 'Lantus',
        manufacturer: 'BioHealth Labs',
        category: 'injections',
        supplier: 'BioHealth Labs',
        batchNumber: 'INS-604',
        manufacturingDate: '2025-02-01',
        expiryDate: '2026-08-12',
        rackLocation: 'D-04',
        strength: '100 IU/mL',
        description: 'Long-acting insulin analogue delivered via prefilled injector pen.',
        barcode: '8901030875429',
        image: null,
        packaging: { packType: 'Box', inventoryUnit: 'Pen', unitsPerPack: 5 },
        stock: { currentPacks: 11, looseUnits: 0, reorderLevel: 6 },
        pricing: { purchasePricePerPack: 55.0, sellingPricePerPack: 62.5 },
        sellingOptions: { allowSellingByPack: true, allowSellingByUnit: true },
    },
    {
        id: 'MED-1010',
        name: 'Diclofenac Gel',
        genericName: 'Diclofenac',
        brandName: 'Voveran Gel',
        manufacturer: 'MedSupply Co',
        category: 'pain-killers',
        supplier: 'MedSupply Co',
        batchNumber: 'DCF-118',
        manufacturingDate: '2025-05-20',
        expiryDate: '2027-01-18',
        rackLocation: 'B-08',
        strength: '1% w/w',
        description: 'Topical anti-inflammatory gel for localized pain and swelling relief.',
        barcode: '8901030875430',
        image: null,
        packaging: { packType: 'Tube', inventoryUnit: 'Gram', unitsPerPack: 30 },
        stock: { currentPacks: 140, looseUnits: 0, reorderLevel: 30 },
        pricing: { purchasePricePerPack: 9.0, sellingPricePerPack: 12.0 },
        sellingOptions: { allowSellingByPack: true, allowSellingByUnit: false },
    },
    {
        id: 'MED-1011',
        name: 'Vitamin C 1000mg',
        genericName: 'Ascorbic Acid',
        brandName: 'Limcee',
        manufacturer: 'NutriPharma',
        category: 'vitamins',
        supplier: 'NutriPharma',
        batchNumber: 'VTC-345',
        manufacturingDate: '2025-06-12',
        expiryDate: '2027-02-05',
        rackLocation: 'E-05',
        strength: '1000mg',
        description: 'Chewable vitamin C tablet to support immune system health.',
        barcode: '8901030875431',
        image: null,
        packaging: { packType: 'Strip', inventoryUnit: 'Tablet', unitsPerPack: 10 },
        stock: { currentPacks: 2, looseUnits: 8, reorderLevel: 10 },
        pricing: { purchasePricePerPack: 4.5, sellingPricePerPack: 6.0 },
        sellingOptions: { allowSellingByPack: true, allowSellingByUnit: true },
    },
    {
        id: 'MED-1012',
        name: 'Ciprofloxacin 500mg',
        genericName: 'Ciprofloxacin',
        brandName: 'Ciplox',
        manufacturer: 'BioHealth Labs',
        category: 'antibiotics',
        supplier: 'BioHealth Labs',
        batchNumber: 'CPR-990',
        manufacturingDate: '2025-01-05',
        expiryDate: '2026-06-15',
        rackLocation: 'A-16',
        strength: '500mg',
        description: 'Fluoroquinolone antibiotic tablet for a broad range of bacterial infections.',
        barcode: '8901030875432',
        image: null,
        packaging: { packType: 'Strip', inventoryUnit: 'Tablet', unitsPerPack: 10 },
        stock: { currentPacks: 21, looseUnits: 0, reorderLevel: 10 },
        pricing: { purchasePricePerPack: 13.0, sellingPricePerPack: 18.0 },
        sellingOptions: { allowSellingByPack: true, allowSellingByUnit: true },
    },
    {
        id: 'MED-1013',
        name: 'Tetanus Toxoid Injection',
        genericName: 'Tetanus Toxoid',
        brandName: 'TT Vaccine',
        manufacturer: 'BioHealth Labs',
        category: 'injections',
        supplier: 'MedAid NGO',
        batchNumber: 'TTX-471',
        manufacturingDate: '2025-03-10',
        expiryDate: '2026-08-09',
        rackLocation: 'D-06',
        strength: '0.5mL',
        description: 'Vaccine used for active immunization against tetanus.',
        barcode: '8901030875433',
        image: null,
        packaging: { packType: 'Vial', inventoryUnit: 'mL', unitsPerPack: 5 },
        stock: { currentPacks: 18, looseUnits: 0, reorderLevel: 5 },
        pricing: { purchasePricePerPack: 15.0, sellingPricePerPack: 20.0 },
        sellingOptions: { allowSellingByPack: true, allowSellingByUnit: false },
    },
    {
        id: 'MED-1014',
        name: 'ORS Sachets',
        genericName: 'Oral Rehydration Salts',
        brandName: 'Electral',
        manufacturer: 'MedSupply Co',
        category: 'syrups',
        supplier: 'MedSupply Co',
        batchNumber: 'ORS-802',
        manufacturingDate: '2025-04-01',
        expiryDate: '2027-09-01',
        rackLocation: 'C-09',
        strength: '21.8g/sachet',
        description: 'Oral rehydration salt sachet for treatment of dehydration.',
        barcode: '8901030875434',
        image: null,
        packaging: { packType: 'Box', inventoryUnit: 'Sachet', unitsPerPack: 25 },
        stock: { currentPacks: 20, looseUnits: 0, reorderLevel: 6 },
        pricing: { purchasePricePerPack: 5.5, sellingPricePerPack: 7.5 },
        sellingOptions: { allowSellingByPack: true, allowSellingByUnit: true },
    },
    {
        id: 'MED-1015',
        name: 'Aspirin 75mg',
        genericName: 'Aspirin',
        brandName: 'Ecosprin',
        manufacturer: 'PharmaCorp Ltd',
        category: 'pain-killers',
        supplier: 'PharmaCorp Ltd',
        batchNumber: 'ASP-266',
        manufacturingDate: '2025-05-15',
        expiryDate: '2026-05-22',
        rackLocation: 'B-11',
        strength: '75mg',
        description: 'Low-dose aspirin tablet used for cardiovascular protection.',
        barcode: '8901030875435',
        image: null,
        packaging: { packType: 'Strip', inventoryUnit: 'Tablet', unitsPerPack: 14 },
        stock: { currentPacks: 0, looseUnits: 5, reorderLevel: 8 },
        pricing: { purchasePricePerPack: 4.2, sellingPricePerPack: 6.0 },
        sellingOptions: { allowSellingByPack: true, allowSellingByUnit: true },
    },
];

// Status priority (worst first): expired > expiring > low-stock > healthy
// Status priority (worst first): expired > expiring > low-stock > healthy
export const getMedicineStatus = (medicine, referenceDate = new Date()) => {
    const expiry = new Date(medicine.expiryDate);
    const msPerDay = 1000 * 60 * 60 * 24;
    const daysToExpiry = Math.ceil((expiry - referenceDate) / msPerDay);

    if (daysToExpiry < 0) return 'expired';
    if (daysToExpiry <= 90) return 'expiring';

    // Calculate total inventory in units
    const totalUnits = calculateTotalUnits(medicine);

    // Convert reorder level from packs to units
    const reorderUnits =
        medicine.stock.reorderLevel * medicine.packaging.unitsPerPack;

    if (totalUnits <= reorderUnits) return 'low-stock';

    return 'healthy';
};

export const statusLabels = {
    expired: 'Expired',
    expiring: 'Expiring Soon',
    'low-stock': 'Low Stock',
    healthy: 'In Stock',
};

export { calculateTotalUnits };